package marketing.implementation;

import boxoffice.database.TicketSale;

import java.sql.*;
import java.util.*;

/**
 * Provides SQL-based access to ticket sales and revenue data for marketing purposes.
 * <p>
 * This class contains methods to query the ticket sales database for performance-based sales,
 * revenue reports, and monthly statistics as required by the Marketing team.
 * </p>
 *
 * <p>
 * It is intended to be used internally by the {@link JDBC} class to execute prepared SQL queries
 * against the database.
 * </p>
 *
 */
public class MarketingAccessImpl {

    /**
     * Retrieves a list of ticket sales for a given performance.
     *
     * @param connection the active SQL connection
     * @param performanceName the name of the performance
     * @return a list of {@link TicketSale} objects
     * @throws SQLException if a database access error occurs
     */
    public List<TicketSale> getTicketSalesBasedOnEvent(Connection connection, String performanceName) throws SQLException {
        List<TicketSale> ticketSales = new ArrayList<>();

        String query = "SELECT ts.* FROM ticket_sale ts " +
                "JOIN performance p ON ts.performance_id = p.performance_id " +
                "WHERE p.title = ?";

        try (PreparedStatement stmt = connection.prepareStatement(query)) {
            stmt.setString(1, performanceName);
            ResultSet rs = stmt.executeQuery();

            while (rs.next()) {
                TicketSale ticketSale = new TicketSale(
                        rs.getInt("ticket_sale_id"),
                        rs.getDouble("price"),
                        rs.getString("customer_id"),
                        rs.getInt("performance_id"),
                        rs.getString("seat_id"),
                        rs.getInt("discount_id"),
                        rs.getInt("group_id"),
                        rs.getInt("staff_id")
                );
                ticketSales.add(ticketSale);
            }
        }

        return ticketSales;
    }

    /**
     * Calculates the total revenue generated by a specific performance.
     *
     * @param connection the active SQL connection
     * @param performanceName the name of the performance
     * @return the total revenue as an integer, or -1 if a query error occurs
     */
    public int getRevenueBasedOnEvent(Connection connection, String performanceName) {
        int totalRevenue = 0;

        String query = "SELECT ts.price FROM ticket_sale ts " +
                "JOIN performance p ON ts.performance_id = p.performance_id " +
                "WHERE p.title = ? AND ts.price > 0";

        try (PreparedStatement stmt = connection.prepareStatement(query)) {
            stmt.setString(1, performanceName);
            ResultSet rs = stmt.executeQuery();

            while (rs.next()) {
                totalRevenue += rs.getDouble("price");
            }

        } catch (SQLException e) {
            e.printStackTrace();
            return -1;
        }

        return totalRevenue;
    }

    /**
     * Generates a revenue report for a specific month and year.
     *
     * @param connection the active SQL connection
     * @param year the year to report on
     * @param month the month to report on (1 = January, ..., 12 = December)
     * @return a map containing keys: revenue (Double), tickets_sold (Integer), first_sale (Timestamp), last_sale (Timestamp)
     * @throws SQLException if a database access error occurs
     */
    public Map<String, Object> getMonthlyRevenueReport(Connection connection, int year, int month) throws SQLException {
        Map<String, Object> report = new HashMap<>();

        String query = "SELECT " +
                "SUM(price) AS monthly_revenue, " +
                "COUNT(*) AS tickets_sold, " +
                "MIN(sale_date) AS first_sale, " +
                "MAX(sale_date) AS last_sale " +
                "FROM ticket_sale " +
                "WHERE price > 0 " +
                "AND YEAR(sale_date) = ? " +
                "AND MONTH(sale_date) = ?";

        try (PreparedStatement stmt = connection.prepareStatement(query)) {
            stmt.setInt(1, year);
            stmt.setInt(2, month);
            ResultSet rs = stmt.executeQuery();

            if (rs.next()) {
                report.put("revenue", rs.getDouble("monthly_revenue"));
                report.put("tickets_sold", rs.getInt("tickets_sold"));
                report.put("first_sale", rs.getTimestamp("first_sale"));
                report.put("last_sale", rs.getTimestamp("last_sale"));
            }
        }

        return report;
    }
}
